name: fl_weather_icons
description: Flutter package for Weather Icons. Weather Icons is a pack of 222 beautifully crafted Open Source icons for representing weather and climate
version: 1.0.3
homepage: https://github.com/rshrc/fl_weather_icons

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  recase: ^4.1.0

flutter:
  fonts:
    - family: WeatherIcons
      fonts:
        - asset: fonts/weathericons.ttf
